# full paper
## dataset: SpermHealth, PolypGen, ATLAS, ISIC2018T1, FIVES, KiTS23, and TissueNet
## module: SI, Link, ViT, MC
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn 1 --fg_vit 1 --fg_vit_se 0 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation
### bottleneck
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 0 --fg_svattn 1 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation
### cross-scale guidance
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_use_guide --fg_vit 1 --fg_vit_se 0 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation
### svattn
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn 0 --fg_vit 1 --fg_vit_se 0 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn -1 --fg_vit 1 --fg_vit_se 0 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn -2 --fg_vit 1 --fg_vit_se 0 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn -3 --fg_vit 1 --fg_vit_se 0 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation
### vit layer
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn 1 --fg_vit 0 --fg_vit_se 0 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn 1 --fg_vit 1 --fg_vit_se 0 --fg_link 2 --fg_link_vit 0 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn 1 --fg_vit 0 --fg_vit_se 0 --fg_link 2 --fg_link_vit 0 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation
### se layer
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 0 --fg_svattn 1 --fg_vit 1 --fg_vit_se 0 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 1 --fg_svattn 1 --fg_vit 1 --fg_vit_se 1 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 1 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn 1 --fg_vit 1 --fg_vit_se 2 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 2 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn 1 --fg_vit 1 --fg_vit_se 1 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 2 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn 1 --fg_vit 1 --fg_vit_se 0 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 2 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn 1 --fg_vit 1 --fg_vit_se 0 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 1 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn 1 --fg_vit 1 --fg_vit_se 1 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn 1 --fg_vit 1 --fg_vit_se 2 --fg_link 2 --fg_link_vit 1 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation
### triangle ablation style (bottleneck + cross-scale guidance + svattn + vit layer)
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 0 --fg_use_guide --fg_svattn 0 --fg_vit 0 --fg_vit_se 0 --fg_link 2 --fg_link_vit 0 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 0 --fg_use_guide --fg_svattn 0 --fg_vit 0 --fg_vit_se 0 --fg_link 2 --fg_link_vit 0 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_use_guide --fg_svattn 0 --fg_vit 0 --fg_vit_se 0 --fg_link 2 --fg_link_vit 0 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation &&
CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --task segmentation --gpus 3 --setname SpermHealth --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name deeplabv3 --seg_feature_guide 2 --fg_start_stage 1 --fg_bottle 1 --fg_bottle_se 2 --fg_svattn 0 --fg_vit 0 --fg_vit_se 0 --fg_link 2 --fg_link_vit 0 --fg_link_vit_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth --exp_base exp_full_ablation